# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newsform.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(742, 713)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget, 0, QtCore.Qt.AlignTop)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout.addWidget(self.comboBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Открыть новость подробнее"))
        self.comboBox.setItemText(0, _translate("MainWindow", "https://tanksgoodnews.com/"))
        self.comboBox.setItemText(1, _translate("MainWindow", "https://www.goodnewsnetwork.org/"))
        self.comboBox.setItemText(2, _translate("MainWindow", "https://www.today.com/news/good-news"))
        self.comboBox.setItemText(3, _translate("MainWindow", "https://www.msn.com/en-us/news/good-news"))
        self.comboBox.setItemText(4, _translate("MainWindow", "https://www.foxnews.com/category/good-news"))
        self.comboBox.setItemText(5, _translate("MainWindow", "https://www.sunnyskyz.com/good-news"))
        self.comboBox.setItemText(6, _translate("MainWindow", "https://www.positive.news/"))
        self.comboBox.setItemText(7, _translate("MainWindow", "https://www.cnn.com/specials/us/the-good-stuff"))
        self.comboBox.setItemText(8, _translate("MainWindow", "https://abcnews.go.com/alerts/good-news"))
        self.comboBox.setItemText(9, _translate("MainWindow", "https://abc7.com/allgoodnews/"))
        self.comboBox.setItemText(10, _translate("MainWindow", "https://www.reddit.com/r/UpliftingNews/"))
        self.comboBox.setItemText(11, _translate("MainWindow", "https://www.goodnet.org/"))
        self.comboBox.setItemText(12, _translate("MainWindow", "https://notallnewsisbad.com/"))
        self.comboBox.setItemText(13, _translate("MainWindow", "https://squirrel-news.net/news/"))
        self.comboBox.setItemText(14, _translate("MainWindow", "https://www.optimistdaily.com/"))
        self.comboBox.setItemText(15, _translate("MainWindow", "https://canoe.com/category/news/good-news/"))
        self.comboBox.setItemText(16, _translate("MainWindow", "https://www.wcpo.com/news/good-news"))
        self.comboBox.setItemText(17, _translate("MainWindow", "https://spectrumlocalnews.com/nys/rochester/news/good-news"))
        self.comboBox.setItemText(18, _translate("MainWindow", "https://www.upworthy.com/"))
        self.comboBox.setItemText(19, _translate("MainWindow", "https://thenewdaily.com.au/news/good-news/"))
        self.comboBox.setItemText(20, _translate("MainWindow", "https://www.cbsnews.com/theuplift/"))
        self.comboBox.setItemText(21, _translate("MainWindow", "https://www.fox2detroit.com/tag/news/good-news-only"))
        self.comboBox.setItemText(22, _translate("MainWindow", "https://www.wowktv.com/news/good-news-with-13/"))
        self.comboBox.setItemText(23, _translate("MainWindow", "https://www.bbc.com/news/topics/cx2pk70323et/uplifting-stories"))
        self.comboBox.setItemText(24, _translate("MainWindow", "https://www.wfmz.com/news/good-news/"))
        self.comboBox.setItemText(25, _translate("MainWindow", "https://www.abc.net.au/news/good-news/"))
        self.comboBox.setItemText(26, _translate("MainWindow", "https://www.globalgoodnews.com/"))
        self.comboBox.setItemText(27, _translate("MainWindow", "https://majically.com/"))
        self.comboBox.setItemText(28, _translate("MainWindow", "https://www.10news.com/positivelysandiego"))
        self.comboBox.setItemText(29, _translate("MainWindow", "https://apnews.com/hub/one-good-thing"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())